-- IKHZKA 退款功能 v1：Refund 扩展为统一申请主表（送达后售后 + 未发货悔单）
ALTER TABLE "Refund" ADD COLUMN IF NOT EXISTS "source" TEXT NOT NULL DEFAULT 'after-sale';
ALTER TABLE "Refund" ADD COLUMN IF NOT EXISTS "type" TEXT;
ALTER TABLE "Refund" ADD COLUMN IF NOT EXISTS "description" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Refund" ADD COLUMN IF NOT EXISTS "images" JSONB;
ALTER TABLE "Refund" ADD COLUMN IF NOT EXISTS "auditBy" TEXT;
ALTER TABLE "Refund" ADD COLUMN IF NOT EXISTS "auditAt" TIMESTAMP(3);
ALTER TABLE "Refund" ADD COLUMN IF NOT EXISTS "auditRemark" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Refund" ADD COLUMN IF NOT EXISTS "wxRefundId" TEXT;
ALTER TABLE "Refund" ADD COLUMN IF NOT EXISTS "refundError" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Refund" ADD COLUMN IF NOT EXISTS "rejectCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Refund" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Refund" ADD COLUMN IF NOT EXISTS "beforeStatus" TEXT NOT NULL DEFAULT '';
-- 旧壳表 reason 非空无默认 → 对齐 schema（悔单原因选填）
ALTER TABLE "Refund" ALTER COLUMN "reason" SET DEFAULT '';
-- 每单一条申请（拒绝后复用同一条重新提交，留痕走审计）
CREATE UNIQUE INDEX IF NOT EXISTS "Refund_orderId_key" ON "Refund"("orderId");
